// <auto-generated />
using Calories_Calculator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calories_Calculator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Calories_Calculator.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "carbohydrates.jpeg",
                            Name = "Carbohydrates"
                        },
                        new
                        {
                            Id = 2,
                            Image = "protein.jpeg",
                            Name = "Protein"
                        },
                        new
                        {
                            Id = 3,
                            Image = "dairy products.jpeg",
                            Name = "Dairy products"
                        },
                        new
                        {
                            Id = 4,
                            Image = "fruit and vegetables.jpeg",
                            Name = "Fruit and vegetables"
                        },
                        new
                        {
                            Id = 5,
                            Image = "fats and sugars.jpeg",
                            Name = "Fats and sugars"
                        });
                });

            modelBuilder.Entity("Calories_Calculator.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calory")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calory = 140,
                            DepartmentId = 1,
                            Image = "white rice.jpeg",
                            Name = "white rice"
                        },
                        new
                        {
                            Id = 2,
                            Calory = 135,
                            DepartmentId = 1,
                            Image = "brown rice.jpg",
                            Name = "brown rice"
                        },
                        new
                        {
                            Id = 3,
                            Calory = 280,
                            DepartmentId = 2,
                            Image = "beef.jpeg",
                            Name = "beef"
                        },
                        new
                        {
                            Id = 4,
                            Calory = 70,
                            DepartmentId = 3,
                            Image = "full fat yogurt.jpeg",
                            Name = "full fat yogurt"
                        },
                        new
                        {
                            Id = 5,
                            Calory = 65,
                            DepartmentId = 4,
                            Image = "banana.jpeg",
                            Name = "banana"
                        });
                });

            modelBuilder.Entity("Calories_Calculator.Models.Food", b =>
                {
                    b.HasOne("Calories_Calculator.Models.Department", "Department")
                        .WithMany("Foods")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Calories_Calculator.Models.Department", b =>
                {
                    b.Navigation("Foods");
                });
#pragma warning restore 612, 618
        }
    }
}
